### ISSUE TITLE
I get an error in Browser "TypeError: _deepmergeTs.deepmerge is not a function" when on 5.x but not on 4.

### ISSUE THREAD

**Issue by ar4hc** [material-table-core/core#586]
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

Sorry, code is to ... to get a small repo out of it, will try later this week.

 
- #### Please try to be as detailed as possible

I have a create-react-app and martial-ui 4.x based (not yet mui 5) project using@material-table/core

After updating to 5.0.x i get the error "TypeError: _deepmergeTs.deepmerge is not a function" in the browser.

yarn tells me:

```
yarn why deepmerge-ts
├─ @material-table/core@npm:5.0.4
│  └─ deepmerge-ts@npm:4.2.1 (via npm:^4.0.3)
│
└─ @material-table/core@npm:5.0.4 [d0642]
   └─ deepmerge-ts@npm:4.2.1 (via npm:^4.0.3)
```

and for deepmerge (without ts):

```
 yarn why deepmerge
├─ @rollup/plugin-node-resolve@npm:11.2.1
│  └─ deepmerge@npm:4.2.2 (via npm:^4.2.2)
│
├─ @rollup/plugin-node-resolve@npm:11.2.1 [e56c9]
│  └─ deepmerge@npm:4.2.2 (via npm:^4.2.2)
│
├─ @svgr/plugin-svgo@npm:5.5.0
│  └─ deepmerge@npm:4.2.2 (via npm:^4.2.2)
│
├─ fork-ts-checker-webpack-plugin@npm:6.5.2
│  └─ deepmerge@npm:4.2.2 (via npm:^4.2.2)
│
├─ fork-ts-checker-webpack-plugin@npm:6.5.2 [83ba0]
│  └─ deepmerge@npm:4.2.2 (via npm:^4.2.2)
│
├─ jest-config@npm:27.5.1
│  └─ deepmerge@npm:4.2.2 (via npm:^4.2.2)
│
└─ jest-config@npm:27.5.1 [c3755]
   └─ deepmerge@npm:4.2.2 (via npm:^4.2.2)```
```

version 4 of material-table has no deepmerge-ts dependency...

How can i debug this ....?

The error is buried deep inside some bundle.js with  300k lines ... :(

i noticed material-tables deepmerge-ts is one patch level behind the version of the "normal" deepmerge.

Is it a webpack problem?

- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Comment by Domino987** [comment]
Hi, yes this seems like a webpack error and should not affect your code, since the base lib does not use ts anyway.
Ill update the version for the next release and maybe this will fix it.

**Comment by hada79** [comment]
I get the same error, running webpack 5.0.1, mui 4,.12.3, material-table/core 5.0.5.

```
Uncaught TypeError: (0 , _deepmergeTs.deepmerge) is not a function
    at LocalizationStore.js:78:1
    at setState (vanilla.js:6:1)
    at mergeLocalization (LocalizationStore.js:76:1)
    at LocalizationStore.js:171:1
    at invokePassiveEffectCreate (react-dom.development.js:23308:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3919:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3968:1)
    at invokeGuardedCallback (react-dom.development.js:4028:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23390:1)
    at unstable_runWithPriority (scheduler.development.js:465:1)
```

Here is LocalizationStore.js in node_modules:

```
var _react = _interopRequireDefault(require("react"));

var _deepmergeTs = require("deepmerge-ts");

var _fastDeepEqual = _interopRequireDefault(require("fast-deep-equal"));
```
I was able to put a breakpoint at the _deepmergeTs, and the value was simply a string to the js file, not the object itself.

Our project is unusable with this error, I am currently looking for a work around.

**Comment by hada79** [comment]
I downgraded material-table/core to 4.3.44 and it works. 

Any way you guys can include changes notes in your versions so I can tell which version to pick?

**Comment by nadavof** [comment]
> I downgraded material-table/core to 4.3.44 and it works.
> 
> Any way you guys can include changes notes in your versions so I can tell which version to pick?

Thanks! I had the same issue and it's working with your solution (downgrade to 4.3.44)

**Comment by 0x6a77** [comment]
workaround: you'll need to exclude the deepmerge cjs module. we use `react-app-rewired` so we can use an exclusion like this:

```
addWebpackModuleRule({
			test: /deepmerge/,
			exclude: /cjs.js/,
		}),
```

**Comment by yvz5** [comment]
we also have the same issue. it started happening lately. any updates on this issue ? 

```
"dependencies": {
        "@emotion/react": "^11.10.4",
        "@emotion/styled": "^11.10.4",
        "@material-table/core": "^0.2.37",
        "@mui/icons-material": "^5.10.6",
        "@mui/material": "^5.10.8",
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "react-router": "^6.4.2",
        "react-router-dom": "^6.4.2"
    },
    "devDependencies": {
        "@types/react": "^18.0.21",
        "@types/react-dom": "^18.0.6",
        "@types/react-router-dom": "^5.3.3",
        "react-scripts": "^5.0.1",
        "typescript": "^4.8.4"
    },
```

**Comment by Domino987** [comment]
No not yet. Can this be reproduced via a sandbox? Did you delete your pakcage-lock file or node modules?

**Comment by yvz5** [comment]
I did delete everything and re installed. if you just create a new react app and add mui with material table, you will see this error message

**Comment by yvz5** [comment]
going back to this combination works: 
`
```JSON
"dependencies": {
        "@emotion/react": "^11.10.4",
        "@emotion/styled": "^11.10.4",
        "@material-table/core": "^0.2.37",
        "@mui/icons-material": "^5.10.6",
        "@mui/material": "^5.10.7",        
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "react-router": "^6.4.1",
        "react-router-dom": "^6.4.1"
    },
    "devDependencies": {
        "@types/react": "^18.0.15",
        "@types/react-dom": "^18.0.6",
        "@types/react-router-dom": "^5.3.3"
}
```

**Comment by MojtabaDaneshi1366** [comment]
same issue, any fix?

**Comment by MojtabaDaneshi1366** [comment]
Solved by using this exact version: consider it hasn't **^ character** in version section.
 "@material-table/core": "0.2.37",

**Comment by yvz5** [comment]
Yes you need to use the exact version. ^ still installs the broken version.

**Comment by Domino987** [comment]
Please try the latest next branch ;)

**Comment by AppointMike** [comment]
@Domino987 Any idea when this is going to be fixed in the latest version? Also can someone explain to me why this started breaking my project for the last few days even though I didn't update the version? Just want to understand what happened so I can learn

**Comment by AppointMike** [comment]
Changing the version did work thought so thank you for providing a fix quickly

**Comment by joshsylvester** [comment]
Sorry to unearth an old issue - but I'm having this same issue on the latest version of the @5.x.x version series (`@meterial-table/core@5.1.12`) and still seeing the `deepmerge` errors -  @Domino987 's comment on Oct8/22 makes it sound like this issue should be fixed in package versions higher than `@5.0.5`.  Downgrading to `@4.3.44` seems to solve the issue, but I'd prefer to be using the highest mui4 supporting version. Is `@material-table/core@4.3.44` the only solution?

**Comment by Domino987** [comment]
I do not see the problem since then. Can you create a sandbox or find a reason ehy this is happening?
