### ISSUE TITLE
Localization still not working on v5.1.1

### ISSUE THREAD

**Issue by nazarroshchuk** [material-table-core/core#612]
# Guidelines

When I trying to use localization props I got an error i console browser, and crash of app 
`localization={{body: {}}}`
Even when I try use like this I am getting: 

Uncaught TypeError: _deepmergeTs.deepmerge is not a function
    node_modules bundle.js:15370
    setState vanilla.js:3
    mergeLocalization LocalizationStore.js:73
    node_modules bundle.js:15463
    React 13
    scheduleRefresh react_devtools_backend.js:6514
    performReactRefresh react-refresh-runtime.development.js:298
    performReactRefresh react-refresh-runtime.development.js:287
    node_modules bundle.js:106576
    setTimeout handler*enqueueUpdate RefreshUtils.js:86
    executeRuntime RefreshUtils.js:249
    $ReactRefreshModuleRuntime$ main.abd3f7bb884ddf7f46ed.hot-update.js:315
    tsx main.abd3f7bb884ddf7f46ed.hot-update.js:328
    factory react refresh:3
    Webpack 18

![2022-09-07_13-50](https://user-images.githubusercontent.com/56605370/188860771-7544464a-a2ad-4950-859b-9f00011c8e46.png)

**Comment by Domino987** [comment]
Can you sahre your package json and recreate it in a sandbox?

**Comment by nazarroshchuk** [comment]
`{
  "name": "panorama-internal",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@emotion/react": "^11.9.3",
    "@emotion/styled": "^11.9.3",
    "@jest/globals": "^28.1.3",
    "@material-table/core": "^5.1.1",
    "@material-ui/core": "^4.12.4",
    "@material-ui/icons": "^4.11.3",
    "@mui/icons-material": "^5.8.4",
    "@mui/lab": "^5.0.0-alpha.89",
    "@mui/material": "^5.8.6",
    "@mui/styles": "^5.8.7",
    "@mui/x-data-grid": "^5.12.3",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^13.0.0",
    "@testing-library/react-hooks": "^8.0.1",
    "@testing-library/user-event": "^13.2.1",
    "@types/jest": "^27.0.1",
    "@types/js-cookie": "^3.0.2",
    "@types/node": "^16.7.13",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "axios": "^0.27.2",
    "date-fns": "^2.28.0",
    "history": "^5.3.0",
    "jest-canvas-mock": "^2.4.0",
    "js-cookie": "^3.0.1",
    "moment": "^2.29.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-double-scrollbar": "^0.0.15",
    "react-router-dom": "^6.3.0",
    "react-scripts": "5.0.1",
    "react-test-renderer": "^18.2.0",
    "recharts": "^2.1.12",
    "sass": "^1.53.0",
    "typescript": "^4.4.2",
    "web-vitals": "^2.1.0"
  },
  "scripts": {
    "start": "GENERATE_SOURCEMAP=false react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test  --setupFiles ./setupTests.js",
    "eject": "react-scripts eject",
    "cypress:e2e": "cypress open"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ],
    "rules": {
      "no-console": "warn",
      "jsx-a11y/aria-role": [
        2,
        {
          "allowedInvalidRoles": [
            "text"
          ],
          "ignoreNonDOM": true
        }
      ]
    }
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "proxy": "http://api:8000",
  "devDependencies": {
    "cypress": "^10.7.0",
    "eslint-plugin-cypress": "^2.12.1",
    "jest-fail-on-console": "^2.4.2"
  }
}`

**Comment by Domino987** [comment]
React 18 is not supported yet
