### ISSUE TITLE
Uncaught TypeError: (0 , _deepmergeTs.deepmerge) is not a function

### ISSUE THREAD

**Issue by sucy6330133** [material-table-core/core#632]
# Guidelines

**Describe the bug**
Failed to load deepmerge-ts after upgrade to 0.2.38.

**To Reproduce**

Cannot reproduce it when using codesandbox to create a example. Weird.

**Expected behavior**
Should load deepmerge-ts successfully.

**Screenshots**
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/9833829/193487779-13517502-be43-4fd2-adc6-f64e0b9d63e4.png">
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/9833829/193487851-996e6bb4-470b-4c11-aef0-0518723deb3f.png">

**Additional context**
Node version: 16.15.1
NPM version: 8.19.1
Material-ui version: 5.10.6

**Comment by Domino987** [comment]
Duplicate for react 18 not supported: https://github.com/material-table-core/core/issues/536

**Comment by 0x6a77** [comment]
work-around: https://github.com/material-table-core/core/issues/586#issuecomment-1265051796
